Attention Entropy
EleutherAI/semantic-memorization pull request #7
Opened 2023-05-31 01:04 UTC by jaydeepborkar

- Changed `max_length=512` to `max_length=64` as we are focusing on the first 64 tokens. The attention of padding might add some noise. But we can stick to 512 if other inferences need that. 

- Attention entropy computation in `save_inference_log()`

2023-05-31 01:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/EleutherAI/semantic-memorization?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/EleutherAI/semantic-memorization?pullRequest=7) before we can accept your contribution.<br/><hr/>**jaydeep** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/EleutherAI/semantic-memorization?pullRequest=7) it.</sub>

2023-06-09 04:12 UTC, Kyle1668 requested changes

2023-06-09 04:12 UTC, Kyle1668 commented on inference.py
> +    #array += 0.0000001
Remove commented out code

2023-06-09 04:12 UTC, Kyle1668 commented on inference.py
> +
Convention is two blank spaces between functions

2023-06-09 04:12 UTC, Kyle1668 commented on inference.py
> +            for layer_index, attention_layer in enumerate(outputs.attentions):
Let's separate this into it's own function somehow.

2023-06-09 04:12 UTC, Kyle1668 commented on inference.py
> +                for head_index, head in enumerate(sequence_attention):
I don't know enough about this method to double-check the formula. I'd recommend getting a second look from Naomi or Katherine.

2023-06-13 22:37 UTC, jaydeepborkar commented on inference.py
> +            for layer_index, attention_layer in enumerate(outputs.attentions):
I thought a bit about this. We are computing metrics for each attention head and saving them for each example. Having access to `index` and `inference_log` makes it easy. Do you have thoughts on how we can go about this?

2023-06-13 22:38 UTC, jaydeepborkar commented on inference.py
> +                for head_index, head in enumerate(sequence_attention):
Sure. Do you mean the logic behind calculating the gini coefficient, correct?

2023-06-27 21:49 UTC, closed without merging